#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename;

use Getopt::Std;
my %opt;
getopts( 'tr', \%opt);

my $t= $opt{t} || 'xt';

foreach my $f (@ARGV)
  { my $base= basename( $f, '.mif', '.mml');
    my $mif= "test/mif/$base.mif";
    my $tmif= "$t/mif/$base.mif";
    my $mml= "test/mml/$base.mml";
    my $tmml= "$t/mml/$base.mml";
    my $cp= "cp '$mif' '$tmif' && cp '$mml' '$tmml'";
    print " $cp\n"; # initial space to not include the command in the shell's history 
    system $cp if $opt{r}; 
  }

__END__
=head1 OPTIONS

  -t <target dir>  move the files to <target dir> (defaults to xt) 
  -r               real: does the cp 
